### ISSUE TITLE
C11

### ISSUE THREAD

**Issue by tpopp** [witchel/adt-utils#5]
When I tried to run make, the UT machines complained about the c11 std.  Do they not have it?

**Comment by witchel** [comment]
Will?

Emmett (from my phone)

**Comment by wyager** [comment]
Yeah, my bad. Looks like lab machines are using outdated GCC. Will push change.

**Comment by tpopp** [comment]
Okay just checked it out. The ut machines never have the newest version of software , so they have gcc version 4.6 when 4.7 is needed. We could probably use c99 by default since the only new feature I can think of us using would be the alignment features. I can work on my computer instead of the ut ones but I don't know if everyone in the group has that option.

**Comment by wyager** [comment]
Gah. Fixed to c99, but there's an issue with some machines thinking uint64 is the llu format specifier, while some think it's the lu format specifier.

**Comment by wyager** [comment]
OK, fixing this up using inttypes.h format specifiers...

**Comment by wyager** [comment]
Builds on lab machines! Had to use inttypes.h to get the format specifiers. I think this resolves the issue, so closing
